/* Generated by Yosys 0.36 (git sha1 8f07a0d8404, clang 15.0.0 -fPIC -Os) */

module counter_4bit(clk, rst, en, co, counter);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire [3:0] _21_;
  wire _22_;
  wire _23_;
  input clk;
  wire clk;
  output co;
  wire co;
  output [3:0] counter;
  wire [3:0] counter;
  wire \counter_reg[0] ;
  wire \counter_reg[1] ;
  wire \counter_reg[2] ;
  wire \counter_reg[3] ;
  input en;
  wire en;
  input rst;
  wire rst;
  AND2_X1 _24_ (
    .A1(\counter_reg[2] ),
    .A2(\counter_reg[1] ),
    .ZN(_05_)
  );
  AND3_X1 _25_ (
    .A1(_05_),
    .A2(\counter_reg[3] ),
    .A3(\counter_reg[0] ),
    .ZN(_20_)
  );
  INV_X1 _26_ (
    .A(_23_),
    .ZN(_00_)
  );
  MUX2_X1 _27_ (
    .A(\counter_reg[0] ),
    .B(_15_),
    .S(_22_),
    .Z(_01_)
  );
  NAND2_X1 _28_ (
    .A1(\counter_reg[0] ),
    .A2(_22_),
    .ZN(_06_)
  );
  XNOR2_X1 _29_ (
    .A(_06_),
    .B(\counter_reg[1] ),
    .ZN(_02_)
  );
  INV_X1 _30_ (
    .A(\counter_reg[2] ),
    .ZN(_07_)
  );
  NAND3_X1 _31_ (
    .A1(\counter_reg[1] ),
    .A2(\counter_reg[0] ),
    .A3(_22_),
    .ZN(_08_)
  );
  NAND2_X1 _32_ (
    .A1(_08_),
    .A2(_07_),
    .ZN(_09_)
  );
  NAND4_X1 _33_ (
    .A1(\counter_reg[2] ),
    .A2(_22_),
    .A3(\counter_reg[1] ),
    .A4(\counter_reg[0] ),
    .ZN(_10_)
  );
  AND2_X1 _34_ (
    .A1(_09_),
    .A2(_10_),
    .ZN(_03_)
  );
  NAND2_X1 _35_ (
    .A1(_10_),
    .A2(\counter_reg[3] ),
    .ZN(_11_)
  );
  INV_X1 _36_ (
    .A(\counter_reg[3] ),
    .ZN(_12_)
  );
  AND2_X1 _37_ (
    .A1(_22_),
    .A2(\counter_reg[0] ),
    .ZN(_13_)
  );
  NAND3_X1 _38_ (
    .A1(_05_),
    .A2(_13_),
    .A3(_12_),
    .ZN(_14_)
  );
  NAND2_X1 _39_ (
    .A1(_14_),
    .A2(_11_),
    .ZN(_04_)
  );
  DFFR_X1 _40_ (
    .CK(_19_),
    .D(_01_),
    .Q(\counter_reg[0] ),
    .QN(_15_),
    .RN(_00_)
  );
  DFFR_X1 _41_ (
    .CK(_19_),
    .D(_02_),
    .Q(\counter_reg[1] ),
    .QN(_18_),
    .RN(_00_)
  );
  DFFR_X1 _42_ (
    .CK(_19_),
    .D(_03_),
    .Q(\counter_reg[2] ),
    .QN(_17_),
    .RN(_00_)
  );
  DFFR_X1 _43_ (
    .CK(_19_),
    .D(_04_),
    .Q(\counter_reg[3] ),
    .QN(_16_),
    .RN(_00_)
  );
  BUF_X1 _44_ (
    .A(clk),
    .Z(_19_)
  );
  BUF_X1 _45_ (
    .A(_20_),
    .Z(co)
  );
  BUF_X1 _46_ (
    .A(_21_[0]),
    .Z(counter[0])
  );
  BUF_X1 _47_ (
    .A(_21_[1]),
    .Z(counter[1])
  );
  BUF_X1 _48_ (
    .A(_21_[2]),
    .Z(counter[2])
  );
  BUF_X1 _49_ (
    .A(_21_[3]),
    .Z(counter[3])
  );
  BUF_X1 _50_ (
    .A(en),
    .Z(_22_)
  );
  BUF_X1 _51_ (
    .A(rst),
    .Z(_23_)
  );
  assign _21_ = { \counter_reg[3] , \counter_reg[2] , \counter_reg[1] , \counter_reg[0]  };
endmodule
