/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module counter(clk, rst, en, clkEn, count, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  input clk;
  input clkEn;
  output co;
  output [3:0] count;
  input en;
  input rst;
  NOT _37_ (
    .A(_31_),
    .Y(_04_)
  );
  NOT _38_ (
    .A(_34_),
    .Y(_05_)
  );
  NOT _39_ (
    .A(_33_),
    .Y(_06_)
  );
  NOT _40_ (
    .A(_32_),
    .Y(_07_)
  );
  NOT _41_ (
    .A(_36_),
    .Y(_08_)
  );
  NAND _42_ (
    .A(_04_),
    .B(_34_),
    .Y(_09_)
  );
  NAND _43_ (
    .A(_06_),
    .B(_32_),
    .Y(_10_)
  );
  NOR _44_ (
    .A(_09_),
    .B(_10_),
    .Y(_30_)
  );
  NAND _45_ (
    .A(_29_),
    .B(_35_),
    .Y(_11_)
  );
  NOR _46_ (
    .A(_04_),
    .B(_11_),
    .Y(_12_)
  );
  NOT _47_ (
    .A(_12_),
    .Y(_13_)
  );
  NAND _48_ (
    .A(_04_),
    .B(_11_),
    .Y(_14_)
  );
  NAND _49_ (
    .A(_08_),
    .B(_14_),
    .Y(_15_)
  );
  NOR _50_ (
    .A(_12_),
    .B(_15_),
    .Y(_00_)
  );
  NOR _51_ (
    .A(_07_),
    .B(_13_),
    .Y(_16_)
  );
  NAND _52_ (
    .A(_32_),
    .B(_12_),
    .Y(_17_)
  );
  NOR _53_ (
    .A(_32_),
    .B(_12_),
    .Y(_18_)
  );
  NOR _54_ (
    .A(_36_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _55_ (
    .A(_17_),
    .B(_19_),
    .Y(_20_)
  );
  NOT _56_ (
    .A(_20_),
    .Y(_01_)
  );
  NAND _57_ (
    .A(_33_),
    .B(_16_),
    .Y(_21_)
  );
  NOR _58_ (
    .A(_33_),
    .B(_16_),
    .Y(_22_)
  );
  NOR _59_ (
    .A(_36_),
    .B(_22_),
    .Y(_23_)
  );
  NAND _60_ (
    .A(_21_),
    .B(_23_),
    .Y(_24_)
  );
  NOT _61_ (
    .A(_24_),
    .Y(_02_)
  );
  NOR _62_ (
    .A(_05_),
    .B(_21_),
    .Y(_25_)
  );
  NAND _63_ (
    .A(_05_),
    .B(_21_),
    .Y(_26_)
  );
  NAND _64_ (
    .A(_08_),
    .B(_26_),
    .Y(_27_)
  );
  NOR _65_ (
    .A(_25_),
    .B(_27_),
    .Y(_03_)
  );
  DFF _66_ (
    .C(_28_),
    .D(_00_),
    .Q(_31_)
  );
  DFF _67_ (
    .C(_28_),
    .D(_01_),
    .Q(_32_)
  );
  DFF _68_ (
    .C(_28_),
    .D(_02_),
    .Q(_33_)
  );
  DFF _69_ (
    .C(_28_),
    .D(_03_),
    .Q(_34_)
  );
  BUF _70_ (
    .A(clk),
    .Y(_28_)
  );
  BUF _71_ (
    .A(clkEn),
    .Y(_29_)
  );
  BUF _72_ (
    .A(_30_),
    .Y(co)
  );
  BUF _73_ (
    .A(_31_),
    .Y(count[0])
  );
  BUF _74_ (
    .A(_32_),
    .Y(count[1])
  );
  BUF _75_ (
    .A(_33_),
    .Y(count[2])
  );
  BUF _76_ (
    .A(_34_),
    .Y(count[3])
  );
  BUF _77_ (
    .A(en),
    .Y(_35_)
  );
  BUF _78_ (
    .A(rst),
    .Y(_36_)
  );
endmodule
