/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module fulladder(i0, i1, ci, s, co);
  input ci;
  output co;
  input i0;
  input i1;
  wire n4;
  wire n5;
  output s;
  XOR2_X1 U5 (
    .A(i1),
    .B(n4),
    .Z(s)
  );
  INV_X1 U6 (
    .A(n5),
    .ZN(co)
  );
  AOI22_X1 U7 (
    .A1(i0),
    .A2(ci),
    .B1(n4),
    .B2(i1),
    .ZN(n5)
  );
  XOR2_X1 U8 (
    .A(ci),
    .B(i0),
    .Z(n4)
  );
endmodule
