/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, clang 13.0.0 -fPIC -Os) */

module fulladder(i0, i1, ci, s, co);
  input ci;
  wire ci;
  output co;
  wire co;
  input i0;
  wire i0;
  input i1;
  wire i1;
  wire n4;
  wire n5;
  output s;
  wire s;
  XOR2_X1 U5 (
    .A(i1),
    .B(n4),
    .Z(s)
  );
  INV_X1 U6 (
    .A(n5),
    .ZN(co)
  );
  AOI22_X1 U7 (
    .A1(i0),
    .A2(ci),
    .B1(n4),
    .B2(i1),
    .ZN(n5)
  );
  XOR2_X1 U8 (
    .A(ci),
    .B(i0),
    .Z(n4)
  );
endmodule
