/* Generated by Yosys 0.30 (git sha1 f7a8284c7b0, clang 14.0.3 -fPIC -Os) */

module aftab_adder(a, b, cin, cout, sum);
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [3:0] sum;
  wire [3:0] sum;
  NAND2_X1 _20_ (
    .A1(b[3]),
    .A2(a[3]),
    .ZN(_0_)
  );
  XOR2_X1 _21_ (
    .A(b[3]),
    .B(a[3]),
    .Z(_1_)
  );
  NAND2_X1 _22_ (
    .A1(b[2]),
    .A2(a[2]),
    .ZN(_2_)
  );
  INV_X1 _23_ (
    .A(b[1]),
    .ZN(_3_)
  );
  INV_X1 _24_ (
    .A(a[1]),
    .ZN(_4_)
  );
  NOR2_X1 _25_ (
    .A1(_3_),
    .A2(_4_),
    .ZN(_5_)
  );
  INV_X1 _26_ (
    .A(cin),
    .ZN(_6_)
  );
  NAND2_X1 _27_ (
    .A1(b[0]),
    .A2(a[0]),
    .ZN(_7_)
  );
  NOR2_X1 _28_ (
    .A1(b[0]),
    .A2(a[0]),
    .ZN(_8_)
  );
  OAI21_X1 _29_ (
    .A(_7_),
    .B1(_8_),
    .B2(_6_),
    .ZN(_9_)
  );
  NAND2_X1 _30_ (
    .A1(_3_),
    .A2(_4_),
    .ZN(_10_)
  );
  AOI21_X1 _31_ (
    .A(_5_),
    .B1(_9_),
    .B2(_10_),
    .ZN(_11_)
  );
  XNOR2_X1 _32_ (
    .A(b[2]),
    .B(a[2]),
    .ZN(_12_)
  );
  OAI21_X1 _33_ (
    .A(_2_),
    .B1(_11_),
    .B2(_12_),
    .ZN(_13_)
  );
  NAND2_X1 _34_ (
    .A1(_13_),
    .A2(_1_),
    .ZN(_14_)
  );
  NAND2_X1 _35_ (
    .A1(_14_),
    .A2(_0_),
    .ZN(cout)
  );
  XNOR2_X1 _36_ (
    .A(b[0]),
    .B(a[0]),
    .ZN(_15_)
  );
  XNOR2_X1 _37_ (
    .A(_15_),
    .B(cin),
    .ZN(sum[0])
  );
  XNOR2_X1 _38_ (
    .A(b[1]),
    .B(a[1]),
    .ZN(_16_)
  );
  XNOR2_X1 _39_ (
    .A(_9_),
    .B(_16_),
    .ZN(sum[1])
  );
  XOR2_X1 _40_ (
    .A(_11_),
    .B(_12_),
    .Z(sum[2])
  );
  OAI211_X1 _41_ (
    .A(_2_),
    .B(_1_),
    .C1(_11_),
    .C2(_12_),
    .ZN(_17_)
  );
  INV_X1 _42_ (
    .A(_1_),
    .ZN(_18_)
  );
  NAND2_X1 _43_ (
    .A1(_13_),
    .A2(_18_),
    .ZN(_19_)
  );
  NAND2_X1 _44_ (
    .A1(_19_),
    .A2(_17_),
    .ZN(sum[3])
  );
endmodule
