/* Generated by Yosys 0.14 (git sha1 UNKNOWN, clang 13.0.0 -fPIC -Os) */

module shiftReg_c17(shiftout, N22, N23, N24, N1, N2, N3, N6, N7, sin, clk, reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input N1;
  wire N1;
  input N2;
  wire N2;
  output N22;
  wire N22;
  output N23;
  wire N23;
  output N24;
  wire N24;
  input N3;
  wire N3;
  input N6;
  wire N6;
  input N7;
  wire N7;
  input clk;
  wire clk;
  wire \inter[0] ;
  wire \inter[1] ;
  wire \inter[2] ;
  wire \inter[3] ;
  wire \inter[4] ;
  wire \inter[5] ;
  wire \inter[6] ;
  wire \inter[7] ;
  input reset;
  wire reset;
  output [7:0] shiftout;
  wire [7:0] shiftout;
  input sin;
  wire sin;
  NAND _14_ (
    .A(_08_),
    .B(_09_),
    .Y(_02_)
  );
  NAND _15_ (
    .A(_05_),
    .B(_02_),
    .Y(_03_)
  );
  NAND _16_ (
    .A(_08_),
    .B(_04_),
    .Y(_00_)
  );
  NAND _17_ (
    .A(_03_),
    .B(_00_),
    .Y(_06_)
  );
  NAND _18_ (
    .A(_10_),
    .B(_02_),
    .Y(_01_)
  );
  NAND _19_ (
    .A(_03_),
    .B(_01_),
    .Y(_07_)
  );
  DFF_PP0 _20_ (
    .C(_11_),
    .D(_13_),
    .Q(\inter[0] ),
    .R(_12_)
  );
  DFF_PP0 _21_ (
    .C(_11_),
    .D(\inter[0] ),
    .Q(\inter[1] ),
    .R(_12_)
  );
  DFF_PP0 _22_ (
    .C(_11_),
    .D(\inter[1] ),
    .Q(\inter[2] ),
    .R(_12_)
  );
  DFF_PP0 _23_ (
    .C(_11_),
    .D(\inter[2] ),
    .Q(\inter[3] ),
    .R(_12_)
  );
  DFF_PP0 _24_ (
    .C(_11_),
    .D(\inter[3] ),
    .Q(\inter[4] ),
    .R(_12_)
  );
  DFF_PP0 _25_ (
    .C(_11_),
    .D(\inter[4] ),
    .Q(\inter[5] ),
    .R(_12_)
  );
  DFF_PP0 _26_ (
    .C(_11_),
    .D(\inter[5] ),
    .Q(\inter[6] ),
    .R(_12_)
  );
  DFF_PP0 _27_ (
    .C(_11_),
    .D(\inter[6] ),
    .Q(\inter[7] ),
    .R(_12_)
  );
  IBUF _28_ (
    .I(N1),
    .O(_04_)
  );
  IBUF _29_ (
    .I(N2),
    .O(_05_)
  );
  OBUF _30_ (
    .I(_06_),
    .O(N22)
  );
  OBUF _31_ (
    .I(_07_),
    .O(N23)
  );
  OBUF _32_ (
    .I(_06_),
    .O(N24)
  );
  IBUF _33_ (
    .I(N3),
    .O(_08_)
  );
  IBUF _34_ (
    .I(N6),
    .O(_09_)
  );
  IBUF _35_ (
    .I(N7),
    .O(_10_)
  );
  IBUF _36_ (
    .I(clk),
    .O(_11_)
  );
  IBUF _37_ (
    .I(reset),
    .O(_12_)
  );
  OBUF _38_ (
    .I(\inter[0] ),
    .O(shiftout[0])
  );
  OBUF _39_ (
    .I(\inter[1] ),
    .O(shiftout[1])
  );
  OBUF _40_ (
    .I(\inter[2] ),
    .O(shiftout[2])
  );
  OBUF _41_ (
    .I(\inter[3] ),
    .O(shiftout[3])
  );
  OBUF _42_ (
    .I(\inter[4] ),
    .O(shiftout[4])
  );
  OBUF _43_ (
    .I(\inter[5] ),
    .O(shiftout[5])
  );
  OBUF _44_ (
    .I(\inter[6] ),
    .O(shiftout[6])
  );
  OBUF _45_ (
    .I(\inter[7] ),
    .O(shiftout[7])
  );
  IBUF _46_ (
    .I(sin),
    .O(_13_)
  );
endmodule
