/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module seqDetector(clk, rst, serIn, serOutValid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  input clk;
  wire \ps[0] ;
  wire \ps[1] ;
  wire \ps[2] ;
  input rst;
  input serIn;
  output serOutValid;
  NOT _19_ (
    .A(_16_),
    .Y(_04_)
  );
  NOT _20_ (
    .A(\ps[1] ),
    .Y(_05_)
  );
  NAND _21_ (
    .A(_04_),
    .B(_17_),
    .Y(_06_)
  );
  NOT _22_ (
    .A(_06_),
    .Y(_07_)
  );
  NOR _23_ (
    .A(_16_),
    .B(\ps[1] ),
    .Y(_08_)
  );
  NOT _24_ (
    .A(_08_),
    .Y(_09_)
  );
  NOR _25_ (
    .A(\ps[0] ),
    .B(_09_),
    .Y(_10_)
  );
  NOR _26_ (
    .A(_07_),
    .B(_10_),
    .Y(_03_)
  );
  NOR _27_ (
    .A(\ps[2] ),
    .B(_18_),
    .Y(_11_)
  );
  NOT _28_ (
    .A(_11_),
    .Y(_12_)
  );
  NOR _29_ (
    .A(\ps[0] ),
    .B(_12_),
    .Y(_13_)
  );
  NOR _30_ (
    .A(_06_),
    .B(_13_),
    .Y(_01_)
  );
  NAND _31_ (
    .A(_04_),
    .B(_12_),
    .Y(_14_)
  );
  NOR _32_ (
    .A(_17_),
    .B(_14_),
    .Y(_00_)
  );
  NOR _33_ (
    .A(_05_),
    .B(_06_),
    .Y(_02_)
  );
  DFF _34_ (
    .C(_15_),
    .D(_03_),
    .Q(\ps[0] )
  );
  DFF _35_ (
    .C(_15_),
    .D(_00_),
    .Q(\ps[1] )
  );
  DFF _36_ (
    .C(_15_),
    .D(_01_),
    .Q(\ps[2] )
  );
  DFF _37_ (
    .C(_15_),
    .D(_02_),
    .Q(_18_)
  );
  BUFX2 _38_ (
    .A(clk),
    .Y(_15_)
  );
  BUFX2 _39_ (
    .A(rst),
    .Y(_16_)
  );
  BUFX2 _40_ (
    .A(serIn),
    .Y(_17_)
  );
  BUFX2 _41_ (
    .A(_18_),
    .Y(serOutValid)
  );
endmodule
