/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module seqDetector(clk, rst, serIn, serOutValid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input clk;
  wire \ps[0] ;
  wire \ps[1] ;
  wire \ps[2] ;
  input rst;
  input serIn;
  output serOutValid;
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _23_ (
    .A(_16_),
    .Y(_04_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _24_ (
    .A(\ps[1] ),
    .Y(_05_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _25_ (
    .A({ _04_, _17_ }),
    .Y(_06_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _26_ (
    .A(_06_),
    .Y(_07_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _27_ (
    .A({ _16_, \ps[1]  }),
    .Y(_08_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _28_ (
    .A(_08_),
    .Y(_09_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _29_ (
    .A({ \ps[0] , _09_ }),
    .Y(_10_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _30_ (
    .A({ _07_, _10_ }),
    .Y(_03_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _31_ (
    .A({ \ps[2] , _18_ }),
    .Y(_11_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _32_ (
    .A(_11_),
    .Y(_12_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _33_ (
    .A({ \ps[0] , _12_ }),
    .Y(_13_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _34_ (
    .A({ _06_, _13_ }),
    .Y(_01_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _35_ (
    .A({ _04_, _12_ }),
    .Y(_14_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _36_ (
    .A({ _17_, _14_ }),
    .Y(_00_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _37_ (
    .A({ _05_, _06_ }),
    .Y(_02_)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _38_ (
    .C(_15_),
    .CE(1'h1),
    .D(_03_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\ps[0] ),
    .R(1'h0),
    .Si(_19_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _39_ (
    .C(_15_),
    .CE(1'h1),
    .D(_00_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\ps[1] ),
    .R(1'h0),
    .Si(_20_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _40_ (
    .C(_15_),
    .CE(1'h1),
    .D(_01_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\ps[2] ),
    .R(1'h0),
    .Si(_21_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _41_ (
    .C(_15_),
    .CE(1'h1),
    .D(_02_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_18_),
    .R(1'h0),
    .Si(_22_),
    .global_reset(1'h0)
  );
  BUFX2 _42_ (
    .A(clk),
    .Y(_15_)
  );
  BUFX2 _43_ (
    .A(rst),
    .Y(_16_)
  );
  BUFX2 _44_ (
    .A(serIn),
    .Y(_17_)
  );
  BUFX2 _45_ (
    .A(_18_),
    .Y(serOutValid)
  );
endmodule
