/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module dff(D, C, CLR, PRE, CE, NbarT, Si, global_reset, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  input C;
  input CE;
  input CLR;
  input D;
  input NbarT;
  input PRE;
  output Q;
  input Si;
  input global_reset;
  wire tmp;
  NOT _30_ (
    .A(_29_),
    .Y(_04_)
  );
  NOT _31_ (
    .A(_25_),
    .Y(_05_)
  );
  NOT _32_ (
    .A(_24_),
    .Y(_06_)
  );
  NOR _33_ (
    .A(_23_),
    .B(_26_),
    .Y(_07_)
  );
  NAND _34_ (
    .A(_04_),
    .B(_07_),
    .Y(_08_)
  );
  NOT _35_ (
    .A(_08_),
    .Y(_09_)
  );
  NAND _36_ (
    .A(tmp),
    .B(_08_),
    .Y(_10_)
  );
  NAND _37_ (
    .A(_02_),
    .B(_09_),
    .Y(_11_)
  );
  NAND _38_ (
    .A(_10_),
    .B(_11_),
    .Y(tmp)
  );
  NOR _39_ (
    .A(_22_),
    .B(tmp),
    .Y(_12_)
  );
  NOT _40_ (
    .A(_12_),
    .Y(_13_)
  );
  NAND _41_ (
    .A(_22_),
    .B(_06_),
    .Y(_14_)
  );
  NAND _42_ (
    .A(_13_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _43_ (
    .A(_05_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _44_ (
    .A(_28_),
    .B(_05_),
    .Y(_17_)
  );
  NOR _45_ (
    .A(_08_),
    .B(_17_),
    .Y(_18_)
  );
  NAND _46_ (
    .A(_16_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _47_ (
    .A(_10_),
    .B(_19_),
    .Y(_01_)
  );
  NAND _48_ (
    .A(_00_),
    .B(tmp),
    .Y(_20_)
  );
  NOT _49_ (
    .A(_20_),
    .Y(_27_)
  );
  BUF _50_ (
    .A(tmp),
    .Y(_03_)
  );
  DFF _51_ (
    .C(_21_),
    .D(_01_),
    .Q(_02_)
  );
  DFF _52_ (
    .C(tmp),
    .D(_03_),
    .Q(_00_)
  );
  IBUF _53_ (
    .I(C),
    .O(_21_)
  );
  IBUF _54_ (
    .I(CE),
    .O(_22_)
  );
  IBUF _55_ (
    .I(CLR),
    .O(_23_)
  );
  IBUF _56_ (
    .I(D),
    .O(_24_)
  );
  IBUF _57_ (
    .I(NbarT),
    .O(_25_)
  );
  IBUF _58_ (
    .I(PRE),
    .O(_26_)
  );
  OBUF _59_ (
    .I(_27_),
    .O(Q)
  );
  IBUF _60_ (
    .I(Si),
    .O(_28_)
  );
  IBUF _61_ (
    .I(global_reset),
    .O(_29_)
  );
endmodule
