/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module dff(D, C, CLR, PRE, CE, NbarT, Si, global_reset, Q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input C;
  input CE;
  input CLR;
  input D;
  input NbarT;
  input PRE;
  output Q;
  input Si;
  input global_reset;
  wire tmp;
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _32_ (
    .in1(_29_),
    .out1(_04_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _33_ (
    .in1(_25_),
    .out1(_05_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _34_ (
    .in1(_24_),
    .out1(_06_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _35_ (
    .in1({ _23_, _26_ }),
    .out1(_07_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _36_ (
    .in1({ _04_, _07_ }),
    .out1(_08_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _37_ (
    .in1(_08_),
    .out1(_09_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _38_ (
    .in1({ tmp, _08_ }),
    .out1(_10_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _39_ (
    .in1({ _02_, _09_ }),
    .out1(_11_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _40_ (
    .in1({ _10_, _11_ }),
    .out1(tmp)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _41_ (
    .in1({ _22_, tmp }),
    .out1(_12_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _42_ (
    .in1(_12_),
    .out1(_13_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _43_ (
    .in1({ _22_, _06_ }),
    .out1(_14_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _44_ (
    .in1({ _13_, _14_ }),
    .out1(_15_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _45_ (
    .in1({ _05_, _15_ }),
    .out1(_16_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _46_ (
    .in1({ _28_, _05_ }),
    .out1(_17_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _47_ (
    .in1({ _08_, _17_ }),
    .out1(_18_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _48_ (
    .in1({ _16_, _18_ }),
    .out1(_19_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _49_ (
    .in1({ _10_, _19_ }),
    .out1(_01_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _50_ (
    .in1({ _00_, tmp }),
    .out1(_20_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _51_ (
    .in1(_20_),
    .out1(_27_)
  );
  bufg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _52_ (
    .in1(tmp),
    .out1(_03_)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _53_ (
    .C(_21_),
    .CE(1'h1),
    .CLR(1'h0),
    .D(_01_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_02_),
    .Si(_30_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _54_ (
    .C(tmp),
    .CE(1'h1),
    .CLR(1'h0),
    .D(_03_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_00_),
    .Si(_31_),
    .global_reset(1'h0)
  );
  pin #(
    .n(32'sd1)
  ) _55_ (
    .in1(C),
    .out1(_21_)
  );
  pin #(
    .n(32'sd1)
  ) _56_ (
    .in1(CE),
    .out1(_22_)
  );
  pin #(
    .n(32'sd1)
  ) _57_ (
    .in1(CLR),
    .out1(_23_)
  );
  pin #(
    .n(32'sd1)
  ) _58_ (
    .in1(D),
    .out1(_24_)
  );
  pin #(
    .n(32'sd1)
  ) _59_ (
    .in1(NbarT),
    .out1(_25_)
  );
  pin #(
    .n(32'sd1)
  ) _60_ (
    .in1(PRE),
    .out1(_26_)
  );
  pout #(
    .n(32'sd1)
  ) _61_ (
    .in1(_27_),
    .out1(Q)
  );
  pin #(
    .n(32'sd1)
  ) _62_ (
    .in1(Si),
    .out1(_28_)
  );
  pin #(
    .n(32'sd1)
  ) _63_ (
    .in1(global_reset),
    .out1(_29_)
  );
endmodule
