/* Generated by Yosys 0.29+23 (git sha1 cdeef5481, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

module register(clk, rst, A, B, C, Q1, Q2, Q3);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input [3:0] C;
  wire [3:0] C;
  wire CK;
  output [3:0] Q1;
  wire [3:0] Q1;
  output [3:0] Q2;
  wire [3:0] Q2;
  output [3:0] Q3;
  wire [3:0] Q3;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire [3:0] _6_;
  wire [3:0] _7_;
  input clk;
  wire clk;
  wire [3:0] cnt;
  input rst;
  wire rst;
  XOR2X1 _10_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_7_[1])
  );
  NAND3X1 _11_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .C(cnt[2]),
    .Y(_3_)
  );
  INVX1 _12_ (
    .A(_3_),
    .Y(_4_)
  );
  AOI21X1 _13_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .C(cnt[2]),
    .Y(_5_)
  );
  NOR2X1 _14_ (
    .A(_5_),
    .B(_4_),
    .Y(_7_[2])
  );
  XNOR2X1 _15_ (
    .A(_3_),
    .B(cnt[3]),
    .Y(_7_[3])
  );
  NAND2X1 _16_ (
    .A(cnt[3]),
    .B(_4_),
    .Y(_1_)
  );
  INVX1 _17_ (
    .A(rst),
    .Y(_2_)
  );
  DFFSR _18_ (
    .CLK(CK),
    .D(C[0]),
    .Q(Q3[0]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _19_ (
    .CLK(CK),
    .D(C[1]),
    .Q(Q3[1]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _20_ (
    .CLK(CK),
    .D(C[2]),
    .Q(Q3[2]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _21_ (
    .CLK(CK),
    .D(C[3]),
    .Q(Q3[3]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _22_ (
    .CLK(clk),
    .D(B[0]),
    .Q(Q2[0]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _23_ (
    .CLK(clk),
    .D(B[1]),
    .Q(Q2[1]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _24_ (
    .CLK(clk),
    .D(B[2]),
    .Q(Q2[2]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _25_ (
    .CLK(clk),
    .D(B[3]),
    .Q(Q2[3]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _26_ (
    .CLK(clk),
    .D(_6_[0]),
    .Q(cnt[0]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _27_ (
    .CLK(clk),
    .D(_7_[1]),
    .Q(cnt[1]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _28_ (
    .CLK(clk),
    .D(_7_[2]),
    .Q(cnt[2]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _29_ (
    .CLK(clk),
    .D(_7_[3]),
    .Q(cnt[3]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _30_ (
    .CLK(CK),
    .D(A[0]),
    .Q(Q1[0]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _31_ (
    .CLK(CK),
    .D(A[1]),
    .Q(Q1[1]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _32_ (
    .CLK(CK),
    .D(A[2]),
    .Q(Q1[2]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _33_ (
    .CLK(CK),
    .D(A[3]),
    .Q(Q1[3]),
    .R(_2_),
    .S(1'h1)
  );
  DFFSR _34_ (
    .CLK(clk),
    .D(_0_),
    .Q(CK),
    .R(_2_),
    .S(1'h1)
  );
  INVX1 _8_ (
    .A(cnt[0]),
    .Y(_6_[0])
  );
  INVX1 _9_ (
    .A(CK),
    .Y(_0_)
  );
  assign _6_[3:1] = cnt[3:1];
  assign _7_[0] = _6_[0];
endmodule
