/* Generated by Yosys 0.29+23 (git sha1 cdeef5481, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

module register(clk, rst, A, B, C, Q1, Q2, Q3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [3:0] _15_;
  wire [3:0] _16_;
  wire [3:0] _17_;
  wire [3:0] _18_;
  wire [3:0] _19_;
  wire [3:0] _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input [3:0] C;
  wire [3:0] C;
  wire CK;
  output [3:0] Q1;
  wire [3:0] Q1;
  output [3:0] Q2;
  wire [3:0] Q2;
  output [3:0] Q3;
  wire [3:0] Q3;
  wire R;
  input clk;
  wire clk;
  wire \cnt[0] ;
  wire \cnt[1] ;
  wire \cnt[2] ;
  wire \cnt[3] ;
  input rst;
  wire rst;
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _40_ (
    .A(\cnt[0] ),
    .Y(_11_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _41_ (
    .A(CK),
    .Y(_00_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _42_ (
    .A(\cnt[1] ),
    .Y(_01_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _43_ (
    .A(\cnt[2] ),
    .Y(_02_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _44_ (
    .A(\cnt[3] ),
    .Y(_03_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _45_ (
    .A({ _11_, _01_ }),
    .Y(_04_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _46_ (
    .A({ \cnt[0] , \cnt[1]  }),
    .Y(_05_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _47_ (
    .A({ \cnt[0] , \cnt[1]  }),
    .Y(_06_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _48_ (
    .A({ _04_, _06_ }),
    .Y(_12_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _49_ (
    .A({ _02_, _05_ }),
    .Y(_07_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _50_ (
    .A({ \cnt[2] , _04_ }),
    .Y(_08_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _51_ (
    .A({ \cnt[2] , _04_ }),
    .Y(_09_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _52_ (
    .A({ _07_, _09_ }),
    .Y(_13_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _53_ (
    .A({ _03_, _08_ }),
    .Y(R)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _54_ (
    .A({ \cnt[3] , _07_ }),
    .Y(_10_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _55_ (
    .A({ R, _10_ }),
    .Y(_14_)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _56_ (
    .C(CK),
    .CE(1'h1),
    .D(_17_[0]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_20_[0]),
    .R(R),
    .Si(_25_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _57_ (
    .C(CK),
    .CE(1'h1),
    .D(_17_[1]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_20_[1]),
    .R(R),
    .Si(_30_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _58_ (
    .C(CK),
    .CE(1'h1),
    .D(_17_[2]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_20_[2]),
    .R(R),
    .Si(_29_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _59_ (
    .C(CK),
    .CE(1'h1),
    .D(_17_[3]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_20_[3]),
    .R(R),
    .Si(_24_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _60_ (
    .C(_21_),
    .CE(1'h1),
    .D(_16_[0]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_19_[0]),
    .R(R),
    .Si(_26_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _61_ (
    .C(_21_),
    .CE(1'h1),
    .D(_16_[1]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_19_[1]),
    .R(R),
    .Si(_31_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _62_ (
    .C(_21_),
    .CE(1'h1),
    .D(_16_[2]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_19_[2]),
    .R(R),
    .Si(_32_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _63_ (
    .C(_21_),
    .CE(1'h1),
    .D(_16_[3]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_19_[3]),
    .R(R),
    .Si(_33_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _64_ (
    .C(_21_),
    .CE(1'h1),
    .D(_11_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\cnt[0] ),
    .R(_22_),
    .Si(_27_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _65_ (
    .C(_21_),
    .CE(1'h1),
    .D(_12_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\cnt[1] ),
    .R(_22_),
    .Si(_34_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _66_ (
    .C(_21_),
    .CE(1'h1),
    .D(_13_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\cnt[2] ),
    .R(_22_),
    .Si(_35_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _67_ (
    .C(_21_),
    .CE(1'h1),
    .D(_14_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(\cnt[3] ),
    .R(_22_),
    .Si(_36_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _68_ (
    .C(CK),
    .CE(1'h1),
    .D(_15_[0]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_18_[0]),
    .R(_22_),
    .Si(_28_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _69_ (
    .C(CK),
    .CE(1'h1),
    .D(_15_[1]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_18_[1]),
    .R(_22_),
    .Si(_37_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _70_ (
    .C(CK),
    .CE(1'h1),
    .D(_15_[2]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_18_[2]),
    .R(_22_),
    .Si(_38_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _71_ (
    .C(CK),
    .CE(1'h1),
    .D(_15_[3]),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(_18_[3]),
    .R(_22_),
    .Si(_39_),
    .global_reset(1'h0)
  );
  dff #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _72_ (
    .C(_21_),
    .CE(1'h1),
    .D(_00_),
    .NbarT(1'h0),
    .PRE(1'h0),
    .Q(CK),
    .R(_22_),
    .Si(_23_),
    .global_reset(1'h0)
  );
  BUFX2 _73_ (
    .A(A[0]),
    .Y(_15_[0])
  );
  BUFX2 _74_ (
    .A(A[1]),
    .Y(_15_[1])
  );
  BUFX2 _75_ (
    .A(A[2]),
    .Y(_15_[2])
  );
  BUFX2 _76_ (
    .A(A[3]),
    .Y(_15_[3])
  );
  BUFX2 _77_ (
    .A(B[0]),
    .Y(_16_[0])
  );
  BUFX2 _78_ (
    .A(B[1]),
    .Y(_16_[1])
  );
  BUFX2 _79_ (
    .A(B[2]),
    .Y(_16_[2])
  );
  BUFX2 _80_ (
    .A(B[3]),
    .Y(_16_[3])
  );
  BUFX2 _81_ (
    .A(C[0]),
    .Y(_17_[0])
  );
  BUFX2 _82_ (
    .A(C[1]),
    .Y(_17_[1])
  );
  BUFX2 _83_ (
    .A(C[2]),
    .Y(_17_[2])
  );
  BUFX2 _84_ (
    .A(C[3]),
    .Y(_17_[3])
  );
  BUFX2 _85_ (
    .A(_18_[0]),
    .Y(Q1[0])
  );
  BUFX2 _86_ (
    .A(_18_[1]),
    .Y(Q1[1])
  );
  BUFX2 _87_ (
    .A(_18_[2]),
    .Y(Q1[2])
  );
  BUFX2 _88_ (
    .A(_18_[3]),
    .Y(Q1[3])
  );
  BUFX2 _89_ (
    .A(_19_[0]),
    .Y(Q2[0])
  );
  BUFX2 _90_ (
    .A(_19_[1]),
    .Y(Q2[1])
  );
  BUFX2 _91_ (
    .A(_19_[2]),
    .Y(Q2[2])
  );
  BUFX2 _92_ (
    .A(_19_[3]),
    .Y(Q2[3])
  );
  BUFX2 _93_ (
    .A(_20_[0]),
    .Y(Q3[0])
  );
  BUFX2 _94_ (
    .A(_20_[1]),
    .Y(Q3[1])
  );
  BUFX2 _95_ (
    .A(_20_[2]),
    .Y(Q3[2])
  );
  BUFX2 _96_ (
    .A(_20_[3]),
    .Y(Q3[3])
  );
  BUFX2 _97_ (
    .A(clk),
    .Y(_21_)
  );
  BUFX2 _98_ (
    .A(rst),
    .Y(_22_)
  );
endmodule
