/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module fulladder(i0, i1, ci, s, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input ci;
  output co;
  input i0;
  input i1;
  output s;
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _17_ (
    .in({ _15_, _12_ }),
    .out(_11_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _18_ (
    .in({ _08_, _10_ }),
    .out(_00_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _19_ (
    .in({ _15_, _12_ }),
    .out(_01_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _20_ (
    .in(_01_),
    .out(_02_)
  );
  nor_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _21_ (
    .in({ _11_, _02_ }),
    .out(_03_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _22_ (
    .in({ _00_, _01_ }),
    .out(_04_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _23_ (
    .in({ _14_, _04_ }),
    .out(_05_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _24_ (
    .in({ _09_, _03_ }),
    .out(_06_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _25_ (
    .in({ _05_, _06_ }),
    .out(_16_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _26_ (
    .in({ _14_, _00_ }),
    .out(_07_)
  );
  nand_n #(
    .n(32'sd2),
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _27_ (
    .in({ _01_, _07_ }),
    .out(_13_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _28_ (
    .in(_15_),
    .out(_08_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _29_ (
    .in(_14_),
    .out(_09_)
  );
  notg #(
    .tphl(32'sd0),
    .tplh(32'sd0)
  ) _30_ (
    .in(_12_),
    .out(_10_)
  );
  pin #(
    .n(32'sd1)
  ) _31_ (
    .in(ci),
    .out(_12_)
  );
  pout #(
    .n(32'sd1)
  ) _32_ (
    .in(_13_),
    .out(co)
  );
  pin #(
    .n(32'sd1)
  ) _33_ (
    .in(i0),
    .out(_14_)
  );
  pin #(
    .n(32'sd1)
  ) _34_ (
    .in(i1),
    .out(_15_)
  );
  pout #(
    .n(32'sd1)
  ) _35_ (
    .in(_16_),
    .out(s)
  );
endmodule
