/* Generated by Yosys 0.30 (git sha1 f7a8284c7b0, clang 14.0.3 -fPIC -Os) */

module counter(clk, rst, en, clkEn, count, co);
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire [3:0] _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input clk;
  wire clk;
  input clkEn;
  wire clkEn;
  output co;
  wire co;
  output [3:0] count;
  wire [3:0] count;
  input en;
  wire en;
  input rst;
  wire rst;
  INV_X1 _24_ (
    .A(count[2]),
    .ZN(_4_)
  );
  AND4_X1 _25_ (
    .A1(_4_),
    .A2(count[3]),
    .A3(count[1]),
    .A4(_20_[0]),
    .ZN(co)
  );
  INV_X1 _26_ (
    .A(count[0]),
    .ZN(_5_)
  );
  NAND2_X1 _27_ (
    .A1(clkEn),
    .A2(en),
    .ZN(_6_)
  );
  INV_X1 _28_ (
    .A(rst),
    .ZN(_7_)
  );
  OAI21_X1 _29_ (
    .A(_7_),
    .B1(_6_),
    .B2(_20_[0]),
    .ZN(_8_)
  );
  AOI21_X1 _30_ (
    .A(_8_),
    .B1(_6_),
    .B2(_5_),
    .ZN(_0_)
  );
  INV_X1 _31_ (
    .A(count[1]),
    .ZN(_9_)
  );
  NAND3_X1 _32_ (
    .A1(clkEn),
    .A2(en),
    .A3(count[0]),
    .ZN(_10_)
  );
  NAND4_X1 _33_ (
    .A1(count[1]),
    .A2(count[0]),
    .A3(clkEn),
    .A4(en),
    .ZN(_11_)
  );
  NAND2_X1 _34_ (
    .A1(_11_),
    .A2(_7_),
    .ZN(_12_)
  );
  AOI21_X1 _35_ (
    .A(_12_),
    .B1(_10_),
    .B2(_9_),
    .ZN(_1_)
  );
  NAND2_X1 _36_ (
    .A1(count[2]),
    .A2(count[1]),
    .ZN(_13_)
  );
  OAI21_X1 _37_ (
    .A(_7_),
    .B1(_10_),
    .B2(_13_),
    .ZN(_14_)
  );
  AOI21_X1 _38_ (
    .A(_14_),
    .B1(_11_),
    .B2(_4_),
    .ZN(_2_)
  );
  OAI21_X1 _39_ (
    .A(count[3]),
    .B1(_10_),
    .B2(_13_),
    .ZN(_15_)
  );
  INV_X1 _40_ (
    .A(count[3]),
    .ZN(_16_)
  );
  AND3_X1 _41_ (
    .A1(count[0]),
    .A2(en),
    .A3(clkEn),
    .ZN(_17_)
  );
  AND2_X1 _42_ (
    .A1(count[1]),
    .A2(count[2]),
    .ZN(_18_)
  );
  NAND3_X1 _43_ (
    .A1(_17_),
    .A2(_16_),
    .A3(_18_),
    .ZN(_19_)
  );
  AOI21_X1 _44_ (
    .A(rst),
    .B1(_19_),
    .B2(_15_),
    .ZN(_3_)
  );
  DFF_X1 _45_ (
    .CK(clk),
    .D(_0_),
    .Q(count[0]),
    .QN(_20_[0])
  );
  DFF_X1 _46_ (
    .CK(clk),
    .D(_1_),
    .Q(count[1]),
    .QN(_23_)
  );
  DFF_X1 _47_ (
    .CK(clk),
    .D(_2_),
    .Q(count[2]),
    .QN(_22_)
  );
  DFF_X1 _48_ (
    .CK(clk),
    .D(_3_),
    .Q(count[3]),
    .QN(_21_)
  );
  assign _20_[3:1] = count[3:1];
endmodule
