/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module counter(clk, rst, en, co, counter);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  input clk;
  output co;
  output [3:0] counter;
  input en;
  input rst;
  NOT _26_ (
    .A(_20_),
    .Y(_04_)
  );
  NOT _27_ (
    .A(_23_),
    .Y(_05_)
  );
  NOT _28_ (
    .A(_24_),
    .Y(_06_)
  );
  NAND _29_ (
    .A(_20_),
    .B(_21_),
    .Y(_07_)
  );
  NAND _30_ (
    .A(_23_),
    .B(_22_),
    .Y(_08_)
  );
  NOR _31_ (
    .A(_07_),
    .B(_08_),
    .Y(_19_)
  );
  NOR _32_ (
    .A(_04_),
    .B(_06_),
    .Y(_09_)
  );
  NOR _33_ (
    .A(_20_),
    .B(_24_),
    .Y(_10_)
  );
  NOR _34_ (
    .A(_09_),
    .B(_10_),
    .Y(_00_)
  );
  NOR _35_ (
    .A(_06_),
    .B(_07_),
    .Y(_11_)
  );
  NOR _36_ (
    .A(_21_),
    .B(_09_),
    .Y(_12_)
  );
  NOR _37_ (
    .A(_11_),
    .B(_12_),
    .Y(_01_)
  );
  NAND _38_ (
    .A(_22_),
    .B(_11_),
    .Y(_13_)
  );
  NOT _39_ (
    .A(_13_),
    .Y(_14_)
  );
  NOR _40_ (
    .A(_22_),
    .B(_11_),
    .Y(_15_)
  );
  NOR _41_ (
    .A(_14_),
    .B(_15_),
    .Y(_02_)
  );
  NOR _42_ (
    .A(_23_),
    .B(_14_),
    .Y(_16_)
  );
  NOR _43_ (
    .A(_05_),
    .B(_13_),
    .Y(_17_)
  );
  NOR _44_ (
    .A(_16_),
    .B(_17_),
    .Y(_03_)
  );
  DFF_PP0 _45_ (
    .C(_18_),
    .D(_00_),
    .Q(_20_),
    .R(_25_)
  );
  DFF_PP0 _46_ (
    .C(_18_),
    .D(_01_),
    .Q(_21_),
    .R(_25_)
  );
  DFF_PP0 _47_ (
    .C(_18_),
    .D(_02_),
    .Q(_22_),
    .R(_25_)
  );
  DFF_PP0 _48_ (
    .C(_18_),
    .D(_03_),
    .Q(_23_),
    .R(_25_)
  );
  IBUF _49_ (
    .I(clk),
    .O(_18_)
  );
  OBUF _50_ (
    .I(_19_),
    .O(co)
  );
  OBUF _51_ (
    .I(_20_),
    .O(counter[0])
  );
  OBUF _52_ (
    .I(_21_),
    .O(counter[1])
  );
  OBUF _53_ (
    .I(_22_),
    .O(counter[2])
  );
  OBUF _54_ (
    .I(_23_),
    .O(counter[3])
  );
  IBUF _55_ (
    .I(en),
    .O(_24_)
  );
  IBUF _56_ (
    .I(rst),
    .O(_25_)
  );
endmodule
