/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module fulladder(i0, i1, ci, s, co);
  wire _0_;
  wire _10_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input ci;
  output co;
  input i0;
  input i1;
  output s;
  INV_X1 _11_ (
    .A(i0),
    .ZN(_8_)
  );
  NAND2_X1 _12_ (
    .A1(i1),
    .A2(ci),
    .ZN(_0_)
  );
  INV_X1 _13_ (
    .A(i1),
    .ZN(_1_)
  );
  INV_X1 _14_ (
    .A(ci),
    .ZN(_2_)
  );
  NAND2_X1 _15_ (
    .A1(_1_),
    .A2(_2_),
    .ZN(_3_)
  );
  NAND3_X1 _16_ (
    .A1(_3_),
    .A2(_8_),
    .A3(_0_),
    .ZN(_4_)
  );
  NAND2_X1 _17_ (
    .A1(_7_),
    .A2(_4_),
    .ZN(_10_)
  );
  OAI21_X1 _18_ (
    .A(_0_),
    .B1(_6_),
    .B2(_8_),
    .ZN(_9_)
  );
  AND2_X1 _19_ (
    .A1(ci),
    .A2(i1),
    .ZN(_5_)
  );
  NOR2_X1 _20_ (
    .A1(i1),
    .A2(ci),
    .ZN(_6_)
  );
  OAI21_X1 _21_ (
    .A(i0),
    .B1(_5_),
    .B2(_6_),
    .ZN(_7_)
  );
  BUF_X1 _22_ (
    .A(_9_),
    .Z(co)
  );
  BUF_X1 _23_ (
    .A(_10_),
    .Z(s)
  );
endmodule