#include <systemc>
#include <uvm>
#include "vip/fi.h"
#include "vip/fi_signal_if.h"
#include "test_lib.h" 
#include "reg/ut_fault_registry.h"
#include "systemC_netlist.h"


using namespace sc_core;

SC_MODULE( testbench ) {

    c432* dut;
    c432* dut_ref;
    fi_signal_if* vif;
    ut_fault_registry* flt_reg;

    SC_HAS_PROCESS(testbench);
    testbench(sc_module_name _name){
        // Interface instantiation
        vif = new fi_signal_if("vif");
          assert(vif);
        // call function to read from file
        std::string input_vector_file = "test_vector.vec";
        // add streams of file to resource database
        // uvm::uvm_resource_db<std::string>::set("*", "input_vector_file", input_vector_file, this);
        uvm::uvm_config_db<std::string>::set(uvm::uvm_root::get(), "*", "input_vector_file", input_vector_file);
        // Add interface to configuration database
        uvm::uvm_config_db<fi_signal_if*>::set(uvm::uvm_root::get(), "*", "vif", vif);
        // Instantiate the DUT and bind ports to interface
        dut = new c432("dut");
            dut->N1.bind(vif->add_and_bind("N1"));
            dut->N4.bind(vif->add_and_bind("N4"));
            dut->N8.bind(vif->add_and_bind("N8"));
            dut->N11.bind(vif->add_and_bind("N11"));
            dut->N14.bind(vif->add_and_bind("N14"));
            dut->N17.bind(vif->add_and_bind("N17"));
            dut->N21.bind(vif->add_and_bind("N21"));
            dut->N24.bind(vif->add_and_bind("N24"));
            dut->N27.bind(vif->add_and_bind("N27"));
            dut->N30.bind(vif->add_and_bind("N30"));
            dut->N34.bind(vif->add_and_bind("N34"));
            dut->N37.bind(vif->add_and_bind("N37"));
            dut->N40.bind(vif->add_and_bind("N40"));
            dut->N43.bind(vif->add_and_bind("N43"));
            dut->N47.bind(vif->add_and_bind("N47"));
            dut->N50.bind(vif->add_and_bind("N50"));
            dut->N53.bind(vif->add_and_bind("N53"));
            dut->N56.bind(vif->add_and_bind("N56"));
            dut->N60.bind(vif->add_and_bind("N60"));
            dut->N63.bind(vif->add_and_bind("N63"));
            dut->N66.bind(vif->add_and_bind("N66"));
            dut->N69.bind(vif->add_and_bind("N69"));
            dut->N73.bind(vif->add_and_bind("N73"));
            dut->N76.bind(vif->add_and_bind("N76"));
            dut->N79.bind(vif->add_and_bind("N79"));
            dut->N82.bind(vif->add_and_bind("N82"));
            dut->N86.bind(vif->add_and_bind("N86"));
            dut->N89.bind(vif->add_and_bind("N89"));
            dut->N92.bind(vif->add_and_bind("N92"));
            dut->N95.bind(vif->add_and_bind("N95"));
            dut->N99.bind(vif->add_and_bind("N99"));
            dut->N102.bind(vif->add_and_bind("N102"));
            dut->N105.bind(vif->add_and_bind("N105"));
            dut->N108.bind(vif->add_and_bind("N108"));
            dut->N112.bind(vif->add_and_bind("N112"));
            dut->N115.bind(vif->add_and_bind("N115"));
            dut->N223.bind(vif->add_and_bind("N223_mod"));
            dut->N329.bind(vif->add_and_bind("N329_mod"));
            dut->N370.bind(vif->add_and_bind("N370_mod"));
            dut->N421.bind(vif->add_and_bind("N421_mod"));
            dut->N430.bind(vif->add_and_bind("N430_mod"));
            dut->N431.bind(vif->add_and_bind("N431_mod"));
            dut->N432.bind(vif->add_and_bind("N432_mod"));
        // Instantiate the DUT and bind ports to interface
        dut_ref = new c432("dut_ref");
            dut_ref->N1.bind(vif->get_signal("N1"));
            dut_ref->N4.bind(vif->get_signal("N4"));
            dut_ref->N8.bind(vif->get_signal("N8"));
            dut_ref->N11.bind(vif->get_signal("N11"));
            dut_ref->N14.bind(vif->get_signal("N14"));
            dut_ref->N17.bind(vif->get_signal("N17"));
            dut_ref->N21.bind(vif->get_signal("N21"));
            dut_ref->N24.bind(vif->get_signal("N24"));
            dut_ref->N27.bind(vif->get_signal("N27"));
            dut_ref->N30.bind(vif->get_signal("N30"));
            dut_ref->N34.bind(vif->get_signal("N34"));
            dut_ref->N37.bind(vif->get_signal("N37"));
            dut_ref->N40.bind(vif->get_signal("N40"));
            dut_ref->N43.bind(vif->get_signal("N43"));
            dut_ref->N47.bind(vif->get_signal("N47"));
            dut_ref->N50.bind(vif->get_signal("N50"));
            dut_ref->N53.bind(vif->get_signal("N53"));
            dut_ref->N56.bind(vif->get_signal("N56"));
            dut_ref->N60.bind(vif->get_signal("N60"));
            dut_ref->N63.bind(vif->get_signal("N63"));
            dut_ref->N66.bind(vif->get_signal("N66"));
            dut_ref->N69.bind(vif->get_signal("N69"));
            dut_ref->N73.bind(vif->get_signal("N73"));
            dut_ref->N76.bind(vif->get_signal("N76"));
            dut_ref->N79.bind(vif->get_signal("N79"));
            dut_ref->N82.bind(vif->get_signal("N82"));
            dut_ref->N86.bind(vif->get_signal("N86"));
            dut_ref->N89.bind(vif->get_signal("N89"));
            dut_ref->N92.bind(vif->get_signal("N92"));
            dut_ref->N95.bind(vif->get_signal("N95"));
            dut_ref->N99.bind(vif->get_signal("N99"));
            dut_ref->N102.bind(vif->get_signal("N102"));
            dut_ref->N105.bind(vif->get_signal("N105"));
            dut_ref->N108.bind(vif->get_signal("N108"));
            dut_ref->N112.bind(vif->get_signal("N112"));
            dut_ref->N115.bind(vif->get_signal("N115"));
            dut_ref->N223.bind(vif->add_and_bind("N223_ref"));
            dut_ref->N329.bind(vif->add_and_bind("N329_ref"));
            dut_ref->N370.bind(vif->add_and_bind("N370_ref"));
            dut_ref->N421.bind(vif->add_and_bind("N421_ref"));
            dut_ref->N430.bind(vif->add_and_bind("N430_ref"));
            dut_ref->N431.bind(vif->add_and_bind("N431_ref"));
            dut_ref->N432.bind(vif->add_and_bind("N432_ref"));
        // creating fault registration module
        flt_reg = new ut_fault_registry();
            flt_reg->add_object(dut->_0_);
            flt_reg->add_object(dut->_100_);
            flt_reg->add_object(dut->_101_);
            flt_reg->add_object(dut->_102_);
            flt_reg->add_object(dut->_103_);
            flt_reg->add_object(dut->_104_);
            flt_reg->add_object(dut->_105_);
            flt_reg->add_object(dut->_106_);
            flt_reg->add_object(dut->_107_);
            flt_reg->add_object(dut->_108_);
            flt_reg->add_object(dut->_109_);
            flt_reg->add_object(dut->_10_);
            flt_reg->add_object(dut->_110_);
            flt_reg->add_object(dut->_111_);
            flt_reg->add_object(dut->_112_);
            flt_reg->add_object(dut->_113_);
            flt_reg->add_object(dut->_114_);
            flt_reg->add_object(dut->_115_);
            flt_reg->add_object(dut->_116_);
            flt_reg->add_object(dut->_117_);
            flt_reg->add_object(dut->_118_);
            flt_reg->add_object(dut->_119_);
            flt_reg->add_object(dut->_11_);
            flt_reg->add_object(dut->_120_);
            flt_reg->add_object(dut->_121_);
            flt_reg->add_object(dut->_122_);
            flt_reg->add_object(dut->_123_);
            flt_reg->add_object(dut->_124_);
            flt_reg->add_object(dut->_125_);
            flt_reg->add_object(dut->_126_);
            flt_reg->add_object(dut->_127_);
            flt_reg->add_object(dut->_128_);
            flt_reg->add_object(dut->_129_);
            flt_reg->add_object(dut->_12_);
            flt_reg->add_object(dut->_130_);
            flt_reg->add_object(dut->_131_);
            flt_reg->add_object(dut->_13_);
            flt_reg->add_object(dut->_14_);
            flt_reg->add_object(dut->_15_);
            flt_reg->add_object(dut->_16_);
            flt_reg->add_object(dut->_17_);
            flt_reg->add_object(dut->_18_);
            flt_reg->add_object(dut->_19_);
            flt_reg->add_object(dut->_1_);
            flt_reg->add_object(dut->_20_);
            flt_reg->add_object(dut->_21_);
            flt_reg->add_object(dut->_22_);
            flt_reg->add_object(dut->_23_);
            flt_reg->add_object(dut->_24_);
            flt_reg->add_object(dut->_25_);
            flt_reg->add_object(dut->_26_);
            flt_reg->add_object(dut->_27_);
            flt_reg->add_object(dut->_28_);
            flt_reg->add_object(dut->_29_);
            flt_reg->add_object(dut->_2_);
            flt_reg->add_object(dut->_30_);
            flt_reg->add_object(dut->_31_);
            flt_reg->add_object(dut->_32_);
            flt_reg->add_object(dut->_33_);
            flt_reg->add_object(dut->_34_);
            flt_reg->add_object(dut->_35_);
            flt_reg->add_object(dut->_36_);
            flt_reg->add_object(dut->_37_);
            flt_reg->add_object(dut->_38_);
            flt_reg->add_object(dut->_39_);
            flt_reg->add_object(dut->_3_);
            flt_reg->add_object(dut->_40_);
            flt_reg->add_object(dut->_41_);
            flt_reg->add_object(dut->_42_);
            flt_reg->add_object(dut->_43_);
            flt_reg->add_object(dut->_44_);
            flt_reg->add_object(dut->_45_);
            flt_reg->add_object(dut->_46_);
            flt_reg->add_object(dut->_47_);
            flt_reg->add_object(dut->_48_);
            flt_reg->add_object(dut->_49_);
            flt_reg->add_object(dut->_4_);
            flt_reg->add_object(dut->_50_);
            flt_reg->add_object(dut->_51_);
            flt_reg->add_object(dut->_52_);
            flt_reg->add_object(dut->_53_);
            flt_reg->add_object(dut->_54_);
            flt_reg->add_object(dut->_55_);
            flt_reg->add_object(dut->_56_);
            flt_reg->add_object(dut->_57_);
            flt_reg->add_object(dut->_58_);
            flt_reg->add_object(dut->_59_);
            flt_reg->add_object(dut->_5_);
            flt_reg->add_object(dut->_60_);
            flt_reg->add_object(dut->_61_);
            flt_reg->add_object(dut->_62_);
            flt_reg->add_object(dut->_63_);
            flt_reg->add_object(dut->_64_);
            flt_reg->add_object(dut->_65_);
            flt_reg->add_object(dut->_66_);
            flt_reg->add_object(dut->_67_);
            flt_reg->add_object(dut->_68_);
            flt_reg->add_object(dut->_69_);
            flt_reg->add_object(dut->_6_);
            flt_reg->add_object(dut->_70_);
            flt_reg->add_object(dut->_71_);
            flt_reg->add_object(dut->_72_);
            flt_reg->add_object(dut->_73_);
            flt_reg->add_object(dut->_74_);
            flt_reg->add_object(dut->_75_);
            flt_reg->add_object(dut->_76_);
            flt_reg->add_object(dut->_77_);
            flt_reg->add_object(dut->_78_);
            flt_reg->add_object(dut->_79_);
            flt_reg->add_object(dut->_7_);
            flt_reg->add_object(dut->_80_);
            flt_reg->add_object(dut->_81_);
            flt_reg->add_object(dut->_82_);
            flt_reg->add_object(dut->_83_);
            flt_reg->add_object(dut->_84_);
            flt_reg->add_object(dut->_85_);
            flt_reg->add_object(dut->_86_);
            flt_reg->add_object(dut->_87_);
            flt_reg->add_object(dut->_88_);
            flt_reg->add_object(dut->_89_);
            flt_reg->add_object(dut->_8_);
            flt_reg->add_object(dut->_90_);
            flt_reg->add_object(dut->_91_);
            flt_reg->add_object(dut->_92_);
            flt_reg->add_object(dut->_93_);
            flt_reg->add_object(dut->_94_);
            flt_reg->add_object(dut->_95_);
            flt_reg->add_object(dut->_96_);
            flt_reg->add_object(dut->_97_);
            flt_reg->add_object(dut->_98_);
            flt_reg->add_object(dut->_99_);
            flt_reg->add_object(dut->_9_);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        // group signals into two 
        vif->set_as_stimulated("N1");
        vif->set_as_stimulated("N4");
        vif->set_as_stimulated("N8");
        vif->set_as_stimulated("N11");
        vif->set_as_stimulated("N14");
        vif->set_as_stimulated("N17");
        vif->set_as_stimulated("N21");
        vif->set_as_stimulated("N24");
        vif->set_as_stimulated("N27");
        vif->set_as_stimulated("N30");
        vif->set_as_stimulated("N34");
        vif->set_as_stimulated("N37");
        vif->set_as_stimulated("N40");
        vif->set_as_stimulated("N43");
        vif->set_as_stimulated("N47");
        vif->set_as_stimulated("N50");
        vif->set_as_stimulated("N53");
        vif->set_as_stimulated("N56");
        vif->set_as_stimulated("N60");
        vif->set_as_stimulated("N63");
        vif->set_as_stimulated("N66");
        vif->set_as_stimulated("N69");
        vif->set_as_stimulated("N73");
        vif->set_as_stimulated("N76");
        vif->set_as_stimulated("N79");
        vif->set_as_stimulated("N82");
        vif->set_as_stimulated("N86");
        vif->set_as_stimulated("N89");
        vif->set_as_stimulated("N92");
        vif->set_as_stimulated("N95");
        vif->set_as_stimulated("N99");
        vif->set_as_stimulated("N102");
        vif->set_as_stimulated("N105");
        vif->set_as_stimulated("N108");
        vif->set_as_stimulated("N112");
        vif->set_as_stimulated("N115");
        vif->set_as_observable_mod("N223_mod");
        vif->set_as_observable_ref("N223_ref");
        vif->set_as_observable_mod("N329_mod");
        vif->set_as_observable_ref("N329_ref");
        vif->set_as_observable_mod("N370_mod");
        vif->set_as_observable_ref("N370_ref");
        vif->set_as_observable_mod("N421_mod");
        vif->set_as_observable_ref("N421_ref");
        vif->set_as_observable_mod("N430_mod");
        vif->set_as_observable_ref("N430_ref");
        vif->set_as_observable_mod("N431_mod");
        vif->set_as_observable_ref("N431_ref");
        vif->set_as_observable_mod("N432_mod");
        vif->set_as_observable_ref("N432_ref");

        // Add interface to configuration database
        uvm::uvm_config_db<ut_fault_registry*>::set(
          uvm::uvm_root::get(), "*", "flt_reg", flt_reg);
    }
};
