/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, clang 13.0.0 -fPIC -Os) */

module MAC( clk, rst, a, b, d);
  wire CK;
  wire [3:0] R1;
  wire [3:0] R2;
  wire _0_;
  wire _10_;
  wire [3:0] _11_;
  wire [3:0] _12_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input clk;
  wire clk;
  output [3:0] d;
  wire [3:0] d;
  input rst;
  wire rst;
  INVX1 _13_ (
    .A(CK),
    .Y(_0_)
  );
  NAND2X1 _14_ (
    .A(R1[0]),
    .B(R2[0]),
    .Y(_2_)
  );
  XOR2X1 _15_ (
    .A(R1[1]),
    .B(R2[1]),
    .Y(_3_)
  );
  XNOR2X1 _16_ (
    .A(_3_),
    .B(_2_),
    .Y(_12_[1])
  );
  NAND2X1 _17_ (
    .A(R1[1]),
    .B(R2[1]),
    .Y(_4_)
  );
  NOR2X1 _18_ (
    .A(R2[1]),
    .B(R1[1]),
    .Y(_5_)
  );
  OAI21X1 _19_ (
    .A(_5_),
    .B(_2_),
    .C(_4_),
    .Y(_6_)
  );
  XOR2X1 _20_ (
    .A(R1[2]),
    .B(R2[2]),
    .Y(_7_)
  );
  XOR2X1 _21_ (
    .A(_6_),
    .B(_7_),
    .Y(_12_[2])
  );
  AND2X2 _22_ (
    .A(R1[2]),
    .B(R2[2]),
    .Y(_8_)
  );
  AOI21X1 _23_ (
    .A(_7_),
    .B(_6_),
    .C(_8_),
    .Y(_9_)
  );
  XOR2X1 _24_ (
    .A(R1[3]),
    .B(R2[3]),
    .Y(_10_)
  );
  XNOR2X1 _25_ (
    .A(_9_),
    .B(_10_),
    .Y(_12_[3])
  );
  XOR2X1 _26_ (
    .A(R1[0]),
    .B(R2[0]),
    .Y(_11_[0])
  );
  INVX1 _27_ (
    .A(rst),
    .Y(_1_)
  );
  DFFSR _28_ (
    .CLK(CK),
    .D(_12_[3]),
    .Q(d[3]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _29_ (
    .CLK(CK),
    .D(b[0]),
    .Q(R2[0]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _30_ (
    .CLK(CK),
    .D(b[1]),
    .Q(R2[1]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _31_ (
    .CLK(CK),
    .D(b[2]),
    .Q(R2[2]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _32_ (
    .CLK(CK),
    .D(b[3]),
    .Q(R2[3]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _33_ (
    .CLK(CK),
    .D(a[0]),
    .Q(R1[0]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _34_ (
    .CLK(CK),
    .D(a[1]),
    .Q(R1[1]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _35_ (
    .CLK(CK),
    .D(a[2]),
    .Q(R1[2]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _36_ (
    .CLK(CK),
    .D(a[3]),
    .Q(R1[3]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _37_ (
    .CLK(clk),
    .D(_0_),
    .Q(CK),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _38_ (
    .CLK(CK),
    .D(_11_[0]),
    .Q(d[0]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _39_ (
    .CLK(CK),
    .D(_12_[1]),
    .Q(d[1]),
    .R(_1_),
    .S(1'h1)
  );
  DFFSR _40_ (
    .CLK(CK),
    .D(_12_[2]),
    .Q(d[2]),
    .R(_1_),
    .S(1'h1)
  );
  assign _12_[0] = _11_[0];
endmodule

