/* Generated by Yosys 0.23+25 (git sha1 13e4f343b, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

module MAC(NBART,clk, rst, a, b, d);
  input NBART;
	wire _MUX0_;
	wire _MUX1_;
	wire _MUX2_;
	wire _MUX3_;
	wire _MUX4_;
	wire _MUX5_;
	wire _MUX6_;
	wire _MUX7_;
	wire _MUX8_;
	wire _MUX9_;
	wire _MUX10_;
	wire _MUX11_;
wire CK;
  wire \R1[0] ;
  wire \R1[1] ;
  wire \R1[2] ;
  wire \R1[3] ;
  wire \R2[0] ;
  wire \R2[1] ;
  wire \R2[2] ;
  wire \R2[3] ;
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input clk;
  wire clk;
  output [3:0] d;
  wire [3:0] d;
  input rst;
  wire rst;
  DFF_PP0 _100_ (
   .C(_MUX0_),
    .D(_42_),
    .Q(_55_),
    .R(_56_)
  );
  DFF_PP0 _101_ (
   .C(_MUX1_),
    .D(_47_),
    .Q(\R2[0] ),
    .R(_56_)
  );
  DFF_PP0 _102_ (
   .C(_MUX2_),
    .D(_48_),
    .Q(\R2[1] ),
    .R(_56_)
  );
  DFF_PP0 _103_ (
   .C(_MUX3_),
    .D(_49_),
    .Q(\R2[2] ),
    .R(_56_)
  );
  DFF_PP0 _104_ (
   .C(_MUX4_),
    .D(_50_),
    .Q(\R2[3] ),
    .R(_56_)
  );
  DFF_PP0 _105_ (
   .C(_MUX5_),
    .D(_43_),
    .Q(\R1[0] ),
    .R(_56_)
  );
  DFF_PP0 _106_ (
   .C(_MUX6_),
    .D(_44_),
    .Q(\R1[1] ),
    .R(_56_)
  );
  DFF_PP0 _107_ (
   .C(_MUX7_),
    .D(_45_),
    .Q(\R1[2] ),
    .R(_56_)
  );
  DFF_PP0 _108_ (
   .C(_MUX8_),
    .D(_46_),
    .Q(\R1[3] ),
    .R(_56_)
  );
  DFF_PP0 _109_ (
    .C(_51_),
    .D(_0_),
    .Q(CK),
    .R(_56_)
  );
  DFF_PP0 _110_ (
   .C(_MUX9_),
    .D(_39_),
    .Q(_52_),
    .R(_56_)
  );
  DFF_PP0 _111_ (
   .C(_MUX10_),
    .D(_40_),
    .Q(_53_),
    .R(_56_)
  );
  DFF_PP0 _112_ (
   .C(_MUX11_),
    .D(_41_),
    .Q(_54_),
    .R(_56_)
  );
  IBUF _113_ (
    .I(a[0]),
    .O(_43_)
  );
  IBUF _114_ (
    .I(a[1]),
    .O(_44_)
  );
  IBUF _115_ (
    .I(a[2]),
    .O(_45_)
  );
  IBUF _116_ (
    .I(a[3]),
    .O(_46_)
  );
  IBUF _117_ (
    .I(b[0]),
    .O(_47_)
  );
  IBUF _118_ (
    .I(b[1]),
    .O(_48_)
  );
  IBUF _119_ (
    .I(b[2]),
    .O(_49_)
  );
  IBUF _120_ (
    .I(b[3]),
    .O(_50_)
  );
  IBUF _121_ (
    .I(clk),
    .O(_51_)
  );
  OBUF _122_ (
    .I(_52_),
    .O(d[0])
  );
  OBUF _123_ (
    .I(_53_),
    .O(d[1])
  );
  OBUF _124_ (
    .I(_54_),
    .O(d[2])
  );
  OBUF _125_ (
    .I(_55_),
    .O(d[3])
  );
  IBUF _126_ (
    .I(rst),
    .O(_56_)
  );
  NOT _57_ (
    .A(\R2[1] ),
    .Y(_1_)
  );
  NOT _58_ (
    .A(\R1[1] ),
    .Y(_2_)
  );
  NOT _59_ (
    .A(\R2[0] ),
    .Y(_3_)
  );
  NOT _60_ (
    .A(\R1[0] ),
    .Y(_4_)
  );
  NOT _61_ (
    .A(\R2[2] ),
    .Y(_5_)
  );
  NOT _62_ (
    .A(\R1[2] ),
    .Y(_6_)
  );
  NOT _63_ (
    .A(CK),
    .Y(_0_)
  );
  NOR _64_ (
    .A(_3_),
    .B(_4_),
    .Y(_7_)
  );
  NAND _65_ (
    .A(\R2[0] ),
    .B(\R1[0] ),
    .Y(_8_)
  );
  NOR _66_ (
    .A(\R2[1] ),
    .B(\R1[1] ),
    .Y(_9_)
  );
  NOT _67_ (
    .A(_9_),
    .Y(_10_)
  );
  NOR _68_ (
    .A(_1_),
    .B(_2_),
    .Y(_11_)
  );
  NAND _69_ (
    .A(\R2[1] ),
    .B(\R1[1] ),
    .Y(_12_)
  );
  NOR _70_ (
    .A(_9_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _71_ (
    .A(_10_),
    .B(_12_),
    .Y(_14_)
  );
  NOR _72_ (
    .A(_8_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _73_ (
    .A(_7_),
    .B(_13_),
    .Y(_16_)
  );
  NOR _74_ (
    .A(_7_),
    .B(_13_),
    .Y(_17_)
  );
  NOR _75_ (
    .A(_15_),
    .B(_17_),
    .Y(_40_)
  );
  NOR _76_ (
    .A(_11_),
    .B(_15_),
    .Y(_18_)
  );
  NAND _77_ (
    .A(_12_),
    .B(_16_),
    .Y(_19_)
  );
  NOR _78_ (
    .A(\R2[2] ),
    .B(\R1[2] ),
    .Y(_20_)
  );
  NOR _79_ (
    .A(_5_),
    .B(_6_),
    .Y(_21_)
  );
  NAND _80_ (
    .A(\R2[2] ),
    .B(\R1[2] ),
    .Y(_22_)
  );
  NOR _81_ (
    .A(_20_),
    .B(_21_),
    .Y(_23_)
  );
  NOT _82_ (
    .A(_23_),
    .Y(_24_)
  );
  NOR _83_ (
    .A(_18_),
    .B(_24_),
    .Y(_25_)
  );
  NAND _84_ (
    .A(_19_),
    .B(_23_),
    .Y(_26_)
  );
  NOR _85_ (
    .A(_19_),
    .B(_23_),
    .Y(_27_)
  );
  NOR _86_ (
    .A(_25_),
    .B(_27_),
    .Y(_41_)
  );
  NOR _87_ (
    .A(_21_),
    .B(_25_),
    .Y(_28_)
  );
  NAND _88_ (
    .A(_22_),
    .B(_26_),
    .Y(_29_)
  );
  NOR _89_ (
    .A(\R2[3] ),
    .B(\R1[3] ),
    .Y(_30_)
  );
  NOT _90_ (
    .A(_30_),
    .Y(_31_)
  );
  NAND _91_ (
    .A(\R2[3] ),
    .B(\R1[3] ),
    .Y(_32_)
  );
  NOT _92_ (
    .A(_32_),
    .Y(_33_)
  );
  NAND _93_ (
    .A(_31_),
    .B(_32_),
    .Y(_34_)
  );
  NOR _94_ (
    .A(_30_),
    .B(_33_),
    .Y(_35_)
  );
  NAND _95_ (
    .A(_28_),
    .B(_35_),
    .Y(_36_)
  );
  NAND _96_ (
    .A(_29_),
    .B(_34_),
    .Y(_37_)
  );
  NAND _97_ (
    .A(_36_),
    .B(_37_),
    .Y(_42_)
  );
  NOR _98_ (
    .A(\R2[0] ),
    .B(\R1[0] ),
    .Y(_38_)
  );
  NOR _99_ (
    .A(_7_),
    .B(_38_),
    .Y(_39_)
  );
	assign _MUX0_ = (NBART) ? CK : clk;
	assign _MUX1_ = (NBART) ? CK : clk;
	assign _MUX2_ = (NBART) ? CK : clk;
	assign _MUX3_ = (NBART) ? CK : clk;
	assign _MUX4_ = (NBART) ? CK : clk;
	assign _MUX5_ = (NBART) ? CK : clk;
	assign _MUX6_ = (NBART) ? CK : clk;
	assign _MUX7_ = (NBART) ? CK : clk;
	assign _MUX8_ = (NBART) ? CK : clk;
	assign _MUX9_ = (NBART) ? CK : clk;
	assign _MUX10_ = (NBART) ? CK : clk;
	assign _MUX11_ = (NBART) ? CK : clk;
endmodule
