
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Frame, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def faultsim():
    FaultSim()


class FaultSim(Frame):
    def __init__(self, parent, controller=None, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent

        # self.geometry("800x600")
        self.configure(bg = "#FFFFFF")


        canvas = Canvas(
            self,
            bg = "#FFFFFF",
            height = 600,
            width = 550,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            1.4210854715202004e-14,
            0.0,
            550.0,
            600.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            0.0,
            0.0,
            550.0,
            8.0,
            fill="#EE5959",
            outline="")

        canvas.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            68.0,
            35.0,
            image=canvas.image_image_1
        )

        canvas.image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = canvas.create_image(
            490.0,
            68.0,
            image=canvas.image_image_2
        )

        canvas.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            self,
            image=canvas.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.place(
            x=28.0,
            y=524.0,
            width=340.0,
            height=37.0
        )

        canvas.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Button(
            self,
            image=canvas.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        button_2.place(
            x=382.0,
            y=469.0,
            width=159.0,
            height=37.0
        )

        canvas.button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        button_3 = Button(
            self,
            image=canvas.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
        button_3.place(
            x=382.0,
            y=362.0,
            width=159.0,
            height=37.0
        )

        canvas.create_text(
            4.0,
            8.0,
            anchor="nw",
            text="Fault ",
            fill="#FFFFFF",
            font=("Inter", 24 * -1)
        )

        canvas.create_text(
            4.0,
            37.0,
            anchor="nw",
            text="Simulation",
            fill="#FFFFFF",
            font=("Inter", 24 * -1)
        )

        canvas.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            198.0,
            336.0,
            image=canvas.entry_image_1
        )
        entry_1 = Text(
            bd=0,
            bg="#EAEAEA",
            highlightthickness=0
        )
        entry_1.place(
            x=28.0,
            y=166.0,
            width=340.0,
            height=338.0
        )

        canvas.create_text(
            28.0,
            122.0,
            anchor="nw",
            text="Simulation Report",
            fill="#000000",
            font=("Inter", 20 * -1)
        )

        canvas.create_rectangle(
            372.0,
            341.0,
            382.2481689453125,
            350.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            372.0,
            444.0,
            382.2481689453125,
            453.0,
            fill="#000000",
            outline="")

        canvas.create_text(
            388.0,
            336.0,
            anchor="nw",
            text="Use existing Fault list",
            fill="#000000",
            font=("Inter", 15 * -1)
        )

        canvas.create_text(
            388.0,
            439.0,
            anchor="nw",
            text="Use existing Test set",
            fill="#000000",
            font=("Inter", 15 * -1)
        )
        # window.resizable(False, False)
        # window.mainloop()
