/* Generated by Yosys 0.10+12 (open-tool-forge build) (git sha1 356ec7bb, clang 11.0.3 ) */

module \sequence (clk, rst, x, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input clk;
  wire \ns[0] ;
  wire \ns[1] ;
  output out;
  wire \ps[0] ;
  wire \ps[1] ;
  input rst;
  input x;
  NOT _10_ (
    .A(\ps[1] ),
    .Y(_03_)
  );
  NOT _11_ (
    .A(_09_),
    .Y(_04_)
  );
  NAND _12_ (
    .A(\ps[1] ),
    .B(\ps[0] ),
    .Y(_05_)
  );
  NOT _13_ (
    .A(_05_),
    .Y(_07_)
  );
  NOR _14_ (
    .A(_03_),
    .B(\ps[0] ),
    .Y(_00_)
  );
  NAND _15_ (
    .A(_09_),
    .B(_00_),
    .Y(_01_)
  );
  NAND _16_ (
    .A(\ps[0] ),
    .B(_04_),
    .Y(_02_)
  );
  NAND _17_ (
    .A(_01_),
    .B(_02_),
    .Y(\ns[1] )
  );
  BUF _18_ (
    .A(_09_),
    .Y(\ns[0] )
  );
  DFF_PP0 _19_ (
    .C(_06_),
    .D(\ns[0] ),
    .Q(\ps[0] ),
    .R(_08_)
  );
  DFF_PP0 _20_ (
    .C(_06_),
    .D(\ns[1] ),
    .Q(\ps[1] ),
    .R(_08_)
  );
  BUF _21_ (
    .A(clk),
    .Y(_06_)
  );
  BUF _22_ (
    .A(_07_),
    .Y(out)
  );
  BUF _23_ (
    .A(rst),
    .Y(_08_)
  );
  BUF _24_ (
    .A(x),
    .Y(_09_)
  );
endmodule
